# Generated by Django 2.2.17 on 2021-02-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20210222_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='views',
            field=models.IntegerField(default=1),
        ),
    ]
